use macroquad::texture::Texture2D;
use once_cell::sync::Lazy;

macro_rules! embed_str {
    ($path:expr) => {{
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", $path))
    }};
}

macro_rules! embed_tex {
    ($path:expr) => {{
        Texture2D::from_file_with_format(
            include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/", $path)),
            None,
        )
    }};
}

#[derive(Debug)]
pub struct EnemyGroupPreset {
    pub id: u8,
    pub name: &'static str,
    pub spawn_interval: usize,
    pub spawn_count: usize,
    pub sprite_idx_base: u8,
    pub boss: bool,
    pub difficulty: u8,
    pub shot_with_rank: bool,
    pub accel_shot_with_rank: bool,
    pub homing_shot_with_rank: bool,
    pub extra_act_with_rank: bool,
    pub accel_with_rank: bool,
    pub x_ini: u8,
    pub y_ini: u8,
    pub assembly: &'static str,
    pub entrypoints: &'static [usize],
}

pub static ENEMY_GROUP_PRESETS: Lazy<[EnemyGroupPreset; 29]> = Lazy::new(|| {
    [
        EnemyGroupPreset {
            id: 0x01,
            name: "Laos",
            spawn_interval: 15,
            spawn_count: 8,
            sprite_idx_base: 0x20,
            boss: false,
            difficulty: 10,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: true,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 238,
            assembly: embed_str!("asset/bytecode-01.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x02,
            name: "Turoa",
            spawn_interval: 4,
            spawn_count: 8,
            sprite_idx_base: 0x22,
            boss: false,
            difficulty: 9,
            shot_with_rank: false,
            accel_shot_with_rank: true,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 232,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-02.asm"),
            entrypoints: &[0x0, 0x2, 0x8, 0xE, 0x0, 0x2, 0x8, 0xE],
        },
        EnemyGroupPreset {
            id: 0x03,
            name: "Ake",
            spawn_interval: 0,
            spawn_count: 5,
            sprite_idx_base: 0x24,
            boss: false,
            difficulty: 12,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 32,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-03.asm"),
            entrypoints: &[0x0, 0x21, 0x1B, 0x15, 0xF],
        },
        EnemyGroupPreset {
            id: 0x04,
            name: "Solad",
            spawn_interval: 15,
            spawn_count: 8,
            sprite_idx_base: 0x27,
            boss: false,
            difficulty: 7,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: true,
            x_ini: 240,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-04.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x05,
            name: "Deda",
            spawn_interval: 10,
            spawn_count: 8,
            sprite_idx_base: 0x28,
            boss: false,
            difficulty: 8,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: true,
            x_ini: 120,
            y_ini: 238,
            assembly: embed_str!("asset/bytecode-05.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x06,
            name: "Pendo",
            spawn_interval: 15,
            spawn_count: 12,
            sprite_idx_base: 0x2A,
            boss: false,
            difficulty: 7,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 168,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-06.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x07,
            name: "Leado",
            spawn_interval: 10,
            spawn_count: 8,
            sprite_idx_base: 0x2D,
            boss: false,
            difficulty: 1,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-07.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x08,
            name: "Bufferfu",
            spawn_interval: 10,
            spawn_count: 8,
            sprite_idx_base: 0x2E,
            boss: false,
            difficulty: 13,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: true,
            x_ini: 0,
            y_ini: 32,
            assembly: embed_str!("asset/bytecode-08.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x09,
            name: "Sirant",
            spawn_interval: 10,
            spawn_count: 16,
            sprite_idx_base: 0x31,
            boss: false,
            difficulty: 1,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 0,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-09.asm"),
            entrypoints: &[
                0x0, 0x22, 0x11, 0x27, 0x31, 0x3B, 0x36, 0x2C, 0x0, 0x36, 0x11, 0x3B, 0x31, 0x27,
                0x22, 0x2C,
            ],
        },
        EnemyGroupPreset {
            id: 0x0A,
            name: "Kargo",
            spawn_interval: 5,
            spawn_count: 8,
            sprite_idx_base: 0x33,
            boss: false,
            difficulty: 8,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: true,
            x_ini: 224,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-10.asm"),
            entrypoints: &[0x0, 0x19, 0x33, 0x3B, 0x0, 0x19, 0x33, 0x3B],
        },
        EnemyGroupPreset {
            id: 0x0B,
            name: "Auteriss",
            spawn_interval: 10,
            spawn_count: 8,
            sprite_idx_base: 0x37,
            boss: false,
            difficulty: 3,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-11.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x0C,
            name: "Merisu",
            spawn_interval: 12,
            spawn_count: 8,
            sprite_idx_base: 0x38,
            boss: false,
            difficulty: 1,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-12.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x0D,
            name: "Pring",
            spawn_interval: 20,
            spawn_count: 8,
            sprite_idx_base: 0x3A,
            boss: false,
            difficulty: 7,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: true,
            x_ini: 0,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-13.asm"),
            entrypoints: &[0x0, 0x7, 0x0, 0x7, 0x0, 0x7, 0x0, 0x7],
        },
        EnemyGroupPreset {
            id: 0x0E,
            name: "Yarl",
            spawn_interval: 8,
            spawn_count: 8,
            sprite_idx_base: 0x3C,
            boss: false,
            difficulty: 1,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-14.asm"),
            entrypoints: &[0x0, 0x39, 0x13, 0x26, 0x0, 0x39, 0x13, 0x26],
        },
        EnemyGroupPreset {
            id: 0x0F,
            name: "Beeq",
            spawn_interval: 20,
            spawn_count: 8,
            sprite_idx_base: 0x3F,
            boss: false,
            difficulty: 11,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: true,
            x_ini: 0,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-15.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x10,
            name: "Mayba",
            spawn_interval: 10,
            spawn_count: 8,
            sprite_idx_base: 0x41,
            boss: false,
            difficulty: 10,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: true,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-16.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x12,
            name: "Jera",
            spawn_interval: 30,
            spawn_count: 8,
            sprite_idx_base: 0x45,
            boss: false,
            difficulty: 9,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: true,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-18.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x13,
            name: "Lydan",
            spawn_interval: 10,
            spawn_count: 8,
            sprite_idx_base: 0x47,
            boss: false,
            difficulty: 15,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: true,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 0,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-19.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x15,
            name: "Beta",
            spawn_interval: 30,
            spawn_count: 8,
            sprite_idx_base: 0x4A,
            boss: false,
            difficulty: 4,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 232,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-21.asm"),
            entrypoints: &[0x0, 0x0, 0x12, 0x12, 0x18, 0x18, 0x1E, 0x1E],
        },
        EnemyGroupPreset {
            id: 0x16,
            name: "Temess",
            spawn_interval: 30,
            spawn_count: 8,
            sprite_idx_base: 0x4C,
            boss: false,
            difficulty: 4,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-22.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x17,
            name: "Patera",
            spawn_interval: 30,
            spawn_count: 8,
            sprite_idx_base: 0x4E,
            boss: false,
            difficulty: 5,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 224,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-23.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0xB, 0xB, 0xB, 0xB],
        },
        EnemyGroupPreset {
            id: 0x18,
            name: "Dorak",
            spawn_interval: 30,
            spawn_count: 8,
            sprite_idx_base: 0x51,
            boss: false,
            difficulty: 15,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: true,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 200,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-24.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x25, 0x25, 0x25, 0x25],
        },
        EnemyGroupPreset {
            id: 0x19,
            name: "Prizon",
            spawn_interval: 30,
            spawn_count: 8,
            sprite_idx_base: 0x55,
            boss: false,
            difficulty: 10,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: true,
            extra_act_with_rank: true,
            accel_with_rank: false,
            x_ini: 0,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-25.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x1A,
            name: "Kadiss",
            spawn_interval: 20,
            spawn_count: 8,
            sprite_idx_base: 0x59,
            boss: false,
            difficulty: 2,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 208,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-26.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x1B,
            name: "Steria",
            spawn_interval: 20,
            spawn_count: 8,
            sprite_idx_base: 0x5C,
            boss: false,
            difficulty: 5,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 0,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-27.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x1C,
            name: "Leda",
            spawn_interval: 10,
            spawn_count: 8,
            sprite_idx_base: 0x5F,
            boss: false,
            difficulty: 3,
            shot_with_rank: true,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 224,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-28.asm"),
            entrypoints: &[0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0],
        },
        EnemyGroupPreset {
            id: 0x1D,
            name: "Guha",
            spawn_interval: 0,
            spawn_count: 2,
            sprite_idx_base: 0x60,
            boss: false,
            difficulty: 11,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: true,
            extra_act_with_rank: true,
            accel_with_rank: false,
            x_ini: 0,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-29.asm"),
            entrypoints: &[0x0, 0xE],
        },
        EnemyGroupPreset {
            id: 0x1E,
            name: "Shidiko",
            spawn_interval: 0,
            spawn_count: 8,
            sprite_idx_base: 0x62,
            boss: true,
            difficulty: 1,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 0,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-30.asm"),
            entrypoints: &[0x18, 0x38, 0x10, 0x30, 0x8, 0x28, 0x0, 0x20],
        },
        EnemyGroupPreset {
            id: 0x1F,
            name: "Lazaro",
            spawn_interval: 0,
            spawn_count: 4,
            sprite_idx_base: 0x72,
            boss: true,
            difficulty: 1,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 0,
            y_ini: 239,
            assembly: embed_str!("asset/bytecode-31.asm"),
            entrypoints: &[0x55, 0x39, 0x1D, 0x0],
        },
    ]
});

pub static METASPRITES: Lazy<[Texture2D; 0x90]> = Lazy::new(|| {
    [
        // {{{
        embed_tex!("asset/metasprite-000.png"),
        embed_tex!("asset/metasprite-001.png"),
        embed_tex!("asset/metasprite-002.png"),
        embed_tex!("asset/metasprite-003.png"),
        embed_tex!("asset/metasprite-004.png"),
        embed_tex!("asset/metasprite-005.png"),
        embed_tex!("asset/metasprite-006.png"),
        embed_tex!("asset/metasprite-007.png"),
        embed_tex!("asset/metasprite-008.png"),
        embed_tex!("asset/metasprite-009.png"),
        embed_tex!("asset/metasprite-010.png"),
        embed_tex!("asset/metasprite-011.png"),
        embed_tex!("asset/metasprite-012.png"),
        embed_tex!("asset/metasprite-013.png"),
        embed_tex!("asset/metasprite-014.png"),
        embed_tex!("asset/metasprite-015.png"),
        embed_tex!("asset/metasprite-016.png"),
        embed_tex!("asset/metasprite-017.png"),
        embed_tex!("asset/metasprite-018.png"),
        embed_tex!("asset/metasprite-019.png"),
        embed_tex!("asset/metasprite-020.png"),
        embed_tex!("asset/metasprite-021.png"),
        embed_tex!("asset/metasprite-022.png"),
        embed_tex!("asset/metasprite-023.png"),
        embed_tex!("asset/metasprite-024.png"),
        embed_tex!("asset/metasprite-025.png"),
        embed_tex!("asset/metasprite-026.png"),
        embed_tex!("asset/metasprite-027.png"),
        embed_tex!("asset/metasprite-028.png"),
        embed_tex!("asset/metasprite-029.png"),
        embed_tex!("asset/metasprite-030.png"),
        embed_tex!("asset/metasprite-031.png"),
        embed_tex!("asset/metasprite-032.png"),
        embed_tex!("asset/metasprite-033.png"),
        embed_tex!("asset/metasprite-034.png"),
        embed_tex!("asset/metasprite-035.png"),
        embed_tex!("asset/metasprite-036.png"),
        embed_tex!("asset/metasprite-037.png"),
        embed_tex!("asset/metasprite-038.png"),
        embed_tex!("asset/metasprite-039.png"),
        embed_tex!("asset/metasprite-040.png"),
        embed_tex!("asset/metasprite-041.png"),
        embed_tex!("asset/metasprite-042.png"),
        embed_tex!("asset/metasprite-043.png"),
        embed_tex!("asset/metasprite-044.png"),
        embed_tex!("asset/metasprite-045.png"),
        embed_tex!("asset/metasprite-046.png"),
        embed_tex!("asset/metasprite-047.png"),
        embed_tex!("asset/metasprite-048.png"),
        embed_tex!("asset/metasprite-049.png"),
        embed_tex!("asset/metasprite-050.png"),
        embed_tex!("asset/metasprite-051.png"),
        embed_tex!("asset/metasprite-052.png"),
        embed_tex!("asset/metasprite-053.png"),
        embed_tex!("asset/metasprite-054.png"),
        embed_tex!("asset/metasprite-055.png"),
        embed_tex!("asset/metasprite-056.png"),
        embed_tex!("asset/metasprite-057.png"),
        embed_tex!("asset/metasprite-058.png"),
        embed_tex!("asset/metasprite-059.png"),
        embed_tex!("asset/metasprite-060.png"),
        embed_tex!("asset/metasprite-061.png"),
        embed_tex!("asset/metasprite-062.png"),
        embed_tex!("asset/metasprite-063.png"),
        embed_tex!("asset/metasprite-064.png"),
        embed_tex!("asset/metasprite-065.png"),
        embed_tex!("asset/metasprite-066.png"),
        embed_tex!("asset/metasprite-067.png"),
        embed_tex!("asset/metasprite-068.png"),
        embed_tex!("asset/metasprite-069.png"),
        embed_tex!("asset/metasprite-070.png"),
        embed_tex!("asset/metasprite-071.png"),
        embed_tex!("asset/metasprite-072.png"),
        embed_tex!("asset/metasprite-073.png"),
        embed_tex!("asset/metasprite-074.png"),
        embed_tex!("asset/metasprite-075.png"),
        embed_tex!("asset/metasprite-076.png"),
        embed_tex!("asset/metasprite-077.png"),
        embed_tex!("asset/metasprite-078.png"),
        embed_tex!("asset/metasprite-079.png"),
        embed_tex!("asset/metasprite-080.png"),
        embed_tex!("asset/metasprite-081.png"),
        embed_tex!("asset/metasprite-082.png"),
        embed_tex!("asset/metasprite-083.png"),
        embed_tex!("asset/metasprite-084.png"),
        embed_tex!("asset/metasprite-085.png"),
        embed_tex!("asset/metasprite-086.png"),
        embed_tex!("asset/metasprite-087.png"),
        embed_tex!("asset/metasprite-088.png"),
        embed_tex!("asset/metasprite-089.png"),
        embed_tex!("asset/metasprite-090.png"),
        embed_tex!("asset/metasprite-091.png"),
        embed_tex!("asset/metasprite-092.png"),
        embed_tex!("asset/metasprite-093.png"),
        embed_tex!("asset/metasprite-094.png"),
        embed_tex!("asset/metasprite-095.png"),
        embed_tex!("asset/metasprite-096.png"),
        embed_tex!("asset/metasprite-097.png"),
        embed_tex!("asset/metasprite-098.png"),
        embed_tex!("asset/metasprite-099.png"),
        embed_tex!("asset/metasprite-100.png"),
        embed_tex!("asset/metasprite-101.png"),
        embed_tex!("asset/metasprite-102.png"),
        embed_tex!("asset/metasprite-103.png"),
        embed_tex!("asset/metasprite-104.png"),
        embed_tex!("asset/metasprite-105.png"),
        embed_tex!("asset/metasprite-106.png"),
        embed_tex!("asset/metasprite-107.png"),
        embed_tex!("asset/metasprite-108.png"),
        embed_tex!("asset/metasprite-109.png"),
        embed_tex!("asset/metasprite-110.png"),
        embed_tex!("asset/metasprite-111.png"),
        embed_tex!("asset/metasprite-112.png"),
        embed_tex!("asset/metasprite-113.png"),
        embed_tex!("asset/metasprite-114.png"),
        embed_tex!("asset/metasprite-115.png"),
        embed_tex!("asset/metasprite-116.png"),
        embed_tex!("asset/metasprite-117.png"),
        embed_tex!("asset/metasprite-118.png"),
        embed_tex!("asset/metasprite-119.png"),
        embed_tex!("asset/metasprite-120.png"),
        embed_tex!("asset/metasprite-121.png"),
        embed_tex!("asset/metasprite-122.png"),
        embed_tex!("asset/metasprite-123.png"),
        embed_tex!("asset/metasprite-124.png"),
        embed_tex!("asset/metasprite-125.png"),
        embed_tex!("asset/metasprite-126.png"),
        embed_tex!("asset/metasprite-127.png"),
        embed_tex!("asset/metasprite-128.png"),
        embed_tex!("asset/metasprite-129.png"),
        embed_tex!("asset/metasprite-130.png"),
        embed_tex!("asset/metasprite-131.png"),
        embed_tex!("asset/metasprite-132.png"),
        embed_tex!("asset/metasprite-133.png"),
        embed_tex!("asset/metasprite-134.png"),
        embed_tex!("asset/metasprite-135.png"),
        embed_tex!("asset/metasprite-136.png"),
        embed_tex!("asset/metasprite-137.png"),
        embed_tex!("asset/metasprite-138.png"),
        embed_tex!("asset/metasprite-139.png"),
        embed_tex!("asset/metasprite-140.png"),
        embed_tex!("asset/metasprite-141.png"),
        embed_tex!("asset/metasprite-142.png"),
        embed_tex!("asset/metasprite-143.png"),
        // }}}
    ]
});
