use macroquad::texture::Texture2D;
use once_cell::sync::Lazy;

macro_rules! embed_str {
    ($path:expr) => {{
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", $path))
    }};
}

macro_rules! embed_tex {
    ($path:expr) => {{
        Texture2D::from_file_with_format(
            include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/", $path)),
            None,
        )
    }};
}

#[derive(Debug)]
pub struct EnemyGroupPreset {
    pub id: u8,
    pub name: &'static str,
    pub spawn_interval: usize,
    pub spawn_count: usize,
    pub sprite_idx_base: u8,
    pub boss: bool,
    pub difficulty: u8,
    pub shot_with_rank: bool,
    pub accel_shot_with_rank: bool,
    pub homing_shot_with_rank: bool,
    pub extra_act_with_rank: bool,
    pub accel_with_rank: bool,
    pub x_ini: u8,
    pub y_ini: u8,
    pub assembly: &'static str,
    pub entrypoints: &'static [usize],
}

pub static ENEMY_GROUP_PRESETS: Lazy<[EnemyGroupPreset; 2]> = Lazy::new(|| {
    [
        EnemyGroupPreset {
            id: 0x01,
            name: "Laos",
            spawn_interval: 15,
            spawn_count: 8,
            sprite_idx_base: 0x20,
            boss: false,
            difficulty: 10,
            shot_with_rank: false,
            accel_shot_with_rank: false,
            homing_shot_with_rank: false,
            extra_act_with_rank: true,
            accel_with_rank: false,
            x_ini: 120,
            y_ini: 238,
            assembly: embed_str!("asset/bytecode-01.asm"),
            entrypoints: &[0; 8],
        },
        EnemyGroupPreset {
            id: 0x02,
            name: "Turoa",
            spawn_interval: 4,
            spawn_count: 8,
            sprite_idx_base: 0x22,
            boss: false,
            difficulty: 9,
            shot_with_rank: false,
            accel_shot_with_rank: true,
            homing_shot_with_rank: false,
            extra_act_with_rank: false,
            accel_with_rank: false,
            x_ini: 232,
            y_ini: 0,
            assembly: embed_str!("asset/bytecode-02.asm"),
            entrypoints: &[0x00, 0x02, 0x08, 0x0E, 0x00, 0x02, 0x08, 0x0E],
        },
    ]
});

pub static ENEMY_SPRITES: Lazy<[Texture2D; 0x90]> = Lazy::new(|| {
    [
        // {{{
        embed_tex!("asset/sprite-enemy-000.png"),
        embed_tex!("asset/sprite-enemy-001.png"),
        embed_tex!("asset/sprite-enemy-002.png"),
        embed_tex!("asset/sprite-enemy-003.png"),
        embed_tex!("asset/sprite-enemy-004.png"),
        embed_tex!("asset/sprite-enemy-005.png"),
        embed_tex!("asset/sprite-enemy-006.png"),
        embed_tex!("asset/sprite-enemy-007.png"),
        embed_tex!("asset/sprite-enemy-008.png"),
        embed_tex!("asset/sprite-enemy-009.png"),
        embed_tex!("asset/sprite-enemy-010.png"),
        embed_tex!("asset/sprite-enemy-011.png"),
        embed_tex!("asset/sprite-enemy-012.png"),
        embed_tex!("asset/sprite-enemy-013.png"),
        embed_tex!("asset/sprite-enemy-014.png"),
        embed_tex!("asset/sprite-enemy-015.png"),
        embed_tex!("asset/sprite-enemy-016.png"),
        embed_tex!("asset/sprite-enemy-017.png"),
        embed_tex!("asset/sprite-enemy-018.png"),
        embed_tex!("asset/sprite-enemy-019.png"),
        embed_tex!("asset/sprite-enemy-020.png"),
        embed_tex!("asset/sprite-enemy-021.png"),
        embed_tex!("asset/sprite-enemy-022.png"),
        embed_tex!("asset/sprite-enemy-023.png"),
        embed_tex!("asset/sprite-enemy-024.png"),
        embed_tex!("asset/sprite-enemy-025.png"),
        embed_tex!("asset/sprite-enemy-026.png"),
        embed_tex!("asset/sprite-enemy-027.png"),
        embed_tex!("asset/sprite-enemy-028.png"),
        embed_tex!("asset/sprite-enemy-029.png"),
        embed_tex!("asset/sprite-enemy-030.png"),
        embed_tex!("asset/sprite-enemy-031.png"),
        embed_tex!("asset/sprite-enemy-032.png"),
        embed_tex!("asset/sprite-enemy-033.png"),
        embed_tex!("asset/sprite-enemy-034.png"),
        embed_tex!("asset/sprite-enemy-035.png"),
        embed_tex!("asset/sprite-enemy-036.png"),
        embed_tex!("asset/sprite-enemy-037.png"),
        embed_tex!("asset/sprite-enemy-038.png"),
        embed_tex!("asset/sprite-enemy-039.png"),
        embed_tex!("asset/sprite-enemy-040.png"),
        embed_tex!("asset/sprite-enemy-041.png"),
        embed_tex!("asset/sprite-enemy-042.png"),
        embed_tex!("asset/sprite-enemy-043.png"),
        embed_tex!("asset/sprite-enemy-044.png"),
        embed_tex!("asset/sprite-enemy-045.png"),
        embed_tex!("asset/sprite-enemy-046.png"),
        embed_tex!("asset/sprite-enemy-047.png"),
        embed_tex!("asset/sprite-enemy-048.png"),
        embed_tex!("asset/sprite-enemy-049.png"),
        embed_tex!("asset/sprite-enemy-050.png"),
        embed_tex!("asset/sprite-enemy-051.png"),
        embed_tex!("asset/sprite-enemy-052.png"),
        embed_tex!("asset/sprite-enemy-053.png"),
        embed_tex!("asset/sprite-enemy-054.png"),
        embed_tex!("asset/sprite-enemy-055.png"),
        embed_tex!("asset/sprite-enemy-056.png"),
        embed_tex!("asset/sprite-enemy-057.png"),
        embed_tex!("asset/sprite-enemy-058.png"),
        embed_tex!("asset/sprite-enemy-059.png"),
        embed_tex!("asset/sprite-enemy-060.png"),
        embed_tex!("asset/sprite-enemy-061.png"),
        embed_tex!("asset/sprite-enemy-062.png"),
        embed_tex!("asset/sprite-enemy-063.png"),
        embed_tex!("asset/sprite-enemy-064.png"),
        embed_tex!("asset/sprite-enemy-065.png"),
        embed_tex!("asset/sprite-enemy-066.png"),
        embed_tex!("asset/sprite-enemy-067.png"),
        embed_tex!("asset/sprite-enemy-068.png"),
        embed_tex!("asset/sprite-enemy-069.png"),
        embed_tex!("asset/sprite-enemy-070.png"),
        embed_tex!("asset/sprite-enemy-071.png"),
        embed_tex!("asset/sprite-enemy-072.png"),
        embed_tex!("asset/sprite-enemy-073.png"),
        embed_tex!("asset/sprite-enemy-074.png"),
        embed_tex!("asset/sprite-enemy-075.png"),
        embed_tex!("asset/sprite-enemy-076.png"),
        embed_tex!("asset/sprite-enemy-077.png"),
        embed_tex!("asset/sprite-enemy-078.png"),
        embed_tex!("asset/sprite-enemy-079.png"),
        embed_tex!("asset/sprite-enemy-080.png"),
        embed_tex!("asset/sprite-enemy-081.png"),
        embed_tex!("asset/sprite-enemy-082.png"),
        embed_tex!("asset/sprite-enemy-083.png"),
        embed_tex!("asset/sprite-enemy-084.png"),
        embed_tex!("asset/sprite-enemy-085.png"),
        embed_tex!("asset/sprite-enemy-086.png"),
        embed_tex!("asset/sprite-enemy-087.png"),
        embed_tex!("asset/sprite-enemy-088.png"),
        embed_tex!("asset/sprite-enemy-089.png"),
        embed_tex!("asset/sprite-enemy-090.png"),
        embed_tex!("asset/sprite-enemy-091.png"),
        embed_tex!("asset/sprite-enemy-092.png"),
        embed_tex!("asset/sprite-enemy-093.png"),
        embed_tex!("asset/sprite-enemy-094.png"),
        embed_tex!("asset/sprite-enemy-095.png"),
        embed_tex!("asset/sprite-enemy-096.png"),
        embed_tex!("asset/sprite-enemy-097.png"),
        embed_tex!("asset/sprite-enemy-098.png"),
        embed_tex!("asset/sprite-enemy-099.png"),
        embed_tex!("asset/sprite-enemy-100.png"),
        embed_tex!("asset/sprite-enemy-101.png"),
        embed_tex!("asset/sprite-enemy-102.png"),
        embed_tex!("asset/sprite-enemy-103.png"),
        embed_tex!("asset/sprite-enemy-104.png"),
        embed_tex!("asset/sprite-enemy-105.png"),
        embed_tex!("asset/sprite-enemy-106.png"),
        embed_tex!("asset/sprite-enemy-107.png"),
        embed_tex!("asset/sprite-enemy-108.png"),
        embed_tex!("asset/sprite-enemy-109.png"),
        embed_tex!("asset/sprite-enemy-110.png"),
        embed_tex!("asset/sprite-enemy-111.png"),
        embed_tex!("asset/sprite-enemy-112.png"),
        embed_tex!("asset/sprite-enemy-113.png"),
        embed_tex!("asset/sprite-enemy-114.png"),
        embed_tex!("asset/sprite-enemy-115.png"),
        embed_tex!("asset/sprite-enemy-116.png"),
        embed_tex!("asset/sprite-enemy-117.png"),
        embed_tex!("asset/sprite-enemy-118.png"),
        embed_tex!("asset/sprite-enemy-119.png"),
        embed_tex!("asset/sprite-enemy-120.png"),
        embed_tex!("asset/sprite-enemy-121.png"),
        embed_tex!("asset/sprite-enemy-122.png"),
        embed_tex!("asset/sprite-enemy-123.png"),
        embed_tex!("asset/sprite-enemy-124.png"),
        embed_tex!("asset/sprite-enemy-125.png"),
        embed_tex!("asset/sprite-enemy-126.png"),
        embed_tex!("asset/sprite-enemy-127.png"),
        embed_tex!("asset/sprite-enemy-128.png"),
        embed_tex!("asset/sprite-enemy-129.png"),
        embed_tex!("asset/sprite-enemy-130.png"),
        embed_tex!("asset/sprite-enemy-131.png"),
        embed_tex!("asset/sprite-enemy-132.png"),
        embed_tex!("asset/sprite-enemy-133.png"),
        embed_tex!("asset/sprite-enemy-134.png"),
        embed_tex!("asset/sprite-enemy-135.png"),
        embed_tex!("asset/sprite-enemy-136.png"),
        embed_tex!("asset/sprite-enemy-137.png"),
        embed_tex!("asset/sprite-enemy-138.png"),
        embed_tex!("asset/sprite-enemy-139.png"),
        embed_tex!("asset/sprite-enemy-140.png"),
        embed_tex!("asset/sprite-enemy-141.png"),
        embed_tex!("asset/sprite-enemy-142.png"),
        embed_tex!("asset/sprite-enemy-143.png"),
        // }}}
    ]
});
